{% set name = "tiledbsoma-ml" %}
{% set version = "0.1.0a4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

# Cheat sheet:
# wget 'https://github.com/single-cell-data/TileDB-SOMA-ML/archive/vi.j.k.tar.gz'
# shasum -a 256 i.j.k.tar.gz
source:
  url: https://github.com/single-cell-data/TileDB-SOMA-ML/archive/v{{ version }}.tar.gz
  sha256: 80f6d77585ec225753ac0717551eaaf3eaf6de19ac563dd61cd9ca460c89afd6

build:
  noarch: python
  script: >-
    SETUPTOOLS_SCM_PRETEND_VERSION="{{ version }}"
    {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [not linux]

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - attrs >=22.2
    - tiledbsoma-py >=1.9.0
    - pytorch >=2.0
    - numpy
    - numba
    - pandas
    - pyarrow
    - scipy

test:
  imports:
    - tiledbsoma_ml
  commands:
    - python -c "import tiledbsoma_ml as soma_ml; print(soma_ml.__version__)" | grep -q {{ version }}
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  source_files:
    - tests/

about:
  summary: Machine learning tools for use with tiledbsoma (SOMA PyTorch loaders)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ryan-williams
    - aaronwolen
    - johnkerl
    - Shelnutt2
    - jdblischak
