{% set name = "tiledbsoma-ml" %}
{% set version = "0.1.0alpha2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

# Cheat sheet:
# wget 'https://github.com/single-cell-data/TileDB-SOMA-ML/archive/i.j.k.tar.gz'
# shasum -a 256 i.j.k.tar.gz
source:
  url: https://github.com/single-cell-data/TileDB-SOMA-ML/archive/{{ version }}.tar.gz
  sha256: ac8733e36accbd427840b844f3d735cb86783132bebc284f31588001b04fadd4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [not linux]

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - attrs >=22.2
    - tiledbsoma-py >=1.9.0
    - pytorch >=2.0
    - torchdata <=0.9
    - numpy
    - numba
    - pandas
    - pyarrow
    - scipy

test:
  imports:
    - tiledbsoma_ml
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  source_files:
    - tests/

about:
  summary: Machine learning tools for use with tiledbsoma (SOMA PyTorch loaders)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ryan-williams
    - aaronwolen
    - johnkerl
    - Shelnutt2
    - jdblischak
